### ISSUE TITLE
Dbus Bluez GattManager1

### ISSUE THREAD

**Issue by GianlucaCucco** [tmds/Tmds.DBus#76] opened 2020-03-10 16:17 UTC
Hi, first of everything i'd like to say thanks for the awesome job done with this library, and thanks to keep the dbus door open for the .net Core!
I'm tring to use the library in order to setup a Raspberry PI 4 as a gattserver, so i'd like to expose some device information and i/o status.
By looking at the official documentation seem that i need to use the api "org.bluez.GattManager1" by passing a hierarchy of items : https://github.com/Vudentz/BlueZ/blob/master/doc/gatt-api.txt (LN 375)

i've used the Tmds.DBus.Tool to generate an interface of org.bluez and i get defined the "org.bluez.GattManager1" but i can't figure out how to use that, i've try several different ways but the best result that i've obtained is "Unhandled exception. System.AggregateException: One or more errors occurred. (org.bluez.Error.Failed: No object received)"
the generated interface is 
`  [DBusInterface("org.bluez.GattManager1")]
    interface IGattManager1 : IDBusObject
    {
        Task RegisterApplicationAsync(ObjectPath Application, IDictionary<string, object> Options);
        Task UnregisterApplicationAsync(ObjectPath Application);
    }`
i've try to change the signature of object path, i've try to use the option dictionary but i'm always get the same error.
The code to create the prox of GattManager is the following:
`  Task.Run(async () =>
            {
                using (var connection = new Connection(Address.System))
                {
                    await connection.ConnectAsync();
					var manager = connection.CreateProxy<IGattManager1>("org.bluez", "/org/bluez/hci0");
				}
			}).Wait();`

Thanks for any help!

**Comment by tmds** [comment] 2020-03-21 16:39
@GianlucaCucco I'm not familiar with this particular API. I know Tmds.DBus gets used for bluez. Maybe if you have a look on GitHub you find the answer you are looking for: https://github.com/search?l=C%23&q=GattManager1&type=Code?

**Comment by GianlucaCucco** [comment] 2020-03-22 16:00
yeah i've already try that way 
my purpose is use that library to start and handle local gatt services as server
i've found a working sample but is written in python https://github.com/Douglas6/cputemp

**Comment by tmds** [comment] 2020-03-25 14:15
If you can run the python code, maybe `dbus-monitor` can help you figure out where things go wrong?

**Comment by danielmeza** [comment] 2020-08-03 21:25
Hi I have the same issue and I get stuck when I need to register the org.bluez.Adapter1 in order to authorize the incoming device 
 connection. That is the correct way to do this https://github.com/PunchThrough/espresso-ble/blob/6e570b2cd34011617c0087dad5ad490439d32dc8/ble.py#L50

**Comment by danielmeza** [comment] 2020-08-04 01:30
I already pass those error but now I get this org.bluez.Error.Failed: No valid service object found

 org.bluez.Error.Failed: No valid service object found
Tmds.DBus.DBusException: org.bluez.Error.Failed: No valid service object found
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)

@tmds any idea?

**Comment by danielmeza** [comment] 2020-09-02 18:19
Hi I have new updates on this issues! I already have an BlueZ app running as a server and it work great! but there are some missing pieces to reach 100% usage of bluez that I can't implement yet those pieces are Notifications. 

This are stopping me to implement notifications https://kernel.googlesource.com/pub/scm/bluetooth/bluez/+/5.50/test/example-gatt-server#200
https://kernel.googlesource.com/pub/scm/bluetooth/bluez/+/5.50/test/example-gatt-server#297
 To implement this I have define the following interfaces 

``` csharp
    [DBusInterface(LocalCharacteristic.GATT_CHART_IFACE)]
    public interface ILocalGattCharacteristic1 : IDBusPropertiesSignal
    {
        Task<byte[]> ReadValueAsync(IDictionary<string, object> Options);

        Task WriteValueAsync(byte[] Value, IDictionary<string, object> Options);

        Task StartNotifyAsync();

        Task StopNotifyAsync();


    }

    [DBusInterface("org.freedesktop.DBus.Properties")]
    public interface IDBusPropertiesSignal : IDBusObject
    {
        Task<IDictionary<string, object>> GetAllAsync();
        Task<IDisposable> WatchPropertiesAsync(Action<PropertyChanges> handler);
    }

```

And here is the implementation 

``` csharp
        public List<Action<PropertyChanges>> propertyChangeHandlers;
        public const string GATT_CHART_IFACE = "org.bluez.GattCharacteristic1";
        public Task<IDictionary<string, object>> GetAllAsync()
        {
            Logger.LogInformation($"Get characteristic {this} properties");
            return Task.FromResult(GetProperties()[GATT_CHART_IFACE]);
        }

        public IDictionary<string, IDictionary<string, object>> GetProperties()
        {
            return new Dictionary<string, IDictionary<string, object>>
            {
                [GATT_CHART_IFACE] = new Dictionary<string, object>()
                {
                    ["Service"] = Service.ObjectPath,
                    ["UUID"] = Uuid,
                    ["Flags"] = Flags,
                    ["Descriptors"] = Descriptors.Select(d => d.ObjectPath).ToArray(),
                    ["Notifiying"] = Notifiying,
                }
            };
        }


        public Task<IDisposable> WatchPropertiesAsync(Action<PropertyChanges> handler)
        {
            Logger.LogInformation($"Registering change property andler for characterisctic {Uuid}");
            propertyChangeHandlers.Add(handler);
            return Task.FromResult<IDisposable>(new PropertiesChangeSubscription(() =>
            {
                propertyChangeHandlers.Remove(handler);
            }));
        }

        protected void OnPropertiesChanged(PropertyChanges chagnes)
        {
            foreach (var handler in propertyChangeHandlers)
            {
                handler?.Invoke(chagnes);
            }
        }

    public class PropertiesChangeSubscription : IDisposable
    {
        public PropertiesChangeSubscription(Action disposeAction)
        {
            DisposeAction = disposeAction;
        }

        public Action DisposeAction { get; }

        public void Dispose()
        {
            DisposeAction?.Invoke();
        }
    }
```

When a Client start a connection the WatchPropertiesAsync is callend with a Action reference withc is stored to callback later when the client start to watch for notifications. Then when the client start to watch the StartNotifyAsync is fired witch start a timer and the timer call the OnPropertiesChanged method on this way. 

``` csharp
        public CustomTimeCharacteristic(Connection connection, AccessControlService service, int index)
           : base(connection, UUID, service, index, GetFlags())
        {
            _timer = new System.Timers.Timer(1000);
            _timer.Elapsed += NotifyTime;

        }

        public override Task StartNotifyAsync()
        {
            Notifiying = true;
            _timer.Start();
            Logger.LogInformation($"Start notify {UUID} characteris");
            return Task.CompletedTask;
        }

        private void NotifyTime(object s, ElapsedEventArgs e)
        {
            OnPropertiesChanged( PropertyChanges.ForProperty("Value", Encoding.UTF8.GetBytes(DateTime.Now.ToString())));
        }
```
But when I call OnPropertiesChanged and then call the Action callbacks the dbus crash. 

@tmds did you have any Idea of how to implement this sceneario?

**Comment by tmds** [comment] 2020-10-23 03:52
@danielmeza I'm not sure if you are reporting an issue with this library or with dbus/bluez. If it is an issue with this library, can you create a new issue with a reproducer.

@GianlucaCucco @danielmeza I am not familiar with bluez dbus interface, so I can't help with specific questions about it. I'm closing the issue.

**Closed by tmds** 2020-10-23 03:52 UTC

**Comment by danielmeza** [comment] 2020-10-23 14:29
@tmds I don't believe that this is a bug on bluez or in this library is just a question about how we can implement a dbus service on c# that produce notification on the remote cliente because that's what bluez does when a characteristic is notifying

**Comment by tmds** [comment] 2020-10-26 14:53
@danielmeza this test does an implementation of `WatchPropertiesAsync`: https://github.com/tmds/Tmds.DBus/blob/b07c3e4d844f076124feb7629a20b5c9dc11d239/test/Tmds.DBus.Tests/PropertyObject.cs#L43-L46.

**Comment by danielmeza** [comment] 2020-10-26 16:41
I will check it out! Thanks

**Comment by danielmeza** [comment] 2021-03-03 18:02
> @danielmeza this test does an implementation of `WatchPropertiesAsync`:
> 
> https://github.com/tmds/Tmds.DBus/blob/b07c3e4d844f076124feb7629a20b5c9dc11d239/test/Tmds.DBus.Tests/PropertyObject.cs#L43-L46
> 
> .

This work like a charm! Now I'm able to use the entire GATT, Read, Write, Notify. Thanks you for your work. 
I had opened this Issue to join this repository to the .NET Foundation. 
https://github.com/tmds/Tmds.DBus/issues/99
