### ISSUE TITLE
Mono crashes when receiving a signal with a struct

### ISSUE THREAD

**Issue by madewokherd** [tmds/Tmds.DBus#155] opened 2022-04-23 22:22 UTC
When running in Mono, receiving a signal that takes a struct type causes a crash when calling the ReadMethodDelegate for that type. Tracing shows that the method itself isn't actually called, the delegate-invoke wrapper crashes.

In fact, it appears that Mono doesn't compile the relevant instance of ReadValueTupleStruct at all.

**Comment by madewokherd** [comment] 2022-04-25 18:03
I'm guessing Mono does not expect a delegate to be constructed for an instance method without an object parameter and called with the instance as an argument.

**Comment by madewokherd** [comment] 2022-04-25 18:24
This is not ideal but works around the problem.
```diff
diff --git a/src/Tmds.DBus/CodeGen/DBusObjectProxy.cs b/src/Tmds.DBus/CodeGen/DBusObjectProxy.cs
index 2fa19e7..a99e34a 100644
--- a/src/Tmds.DBus/CodeGen/DBusObjectProxy.cs
+++ b/src/Tmds.DBus/CodeGen/DBusObjectProxy.cs
@@ -54,7 +54,7 @@ internal protected async Task<IDisposable> WatchNonVoidSignalAsync<T>(string ifa
                     }
                     reader.SetSkipNextStructPadding();
                 }
-                var value = readValue(reader);
+                T value = (T)reader.Read(typeof(T));
                 wrappedDisposable.Call(action, value);
             };
```

I think in order to avoid this pattern, you would have to change `CreateReadMethodForType` to return a static method taking a single MessageReader as an argument, rather than an instance method on MessageReader. But, I haven't confirmed yet that this would fix the crash.

**Comment by madewokherd** [comment] 2022-04-25 18:35
This also works around the crash:
```diff
diff --git a/src/Tmds.DBus/CodeGen/ReadMethodFactory.cs b/src/Tmds.DBus/CodeGen/ReadMethodFactory.cs
index 5e9d434..7820e36 100644
--- a/src/Tmds.DBus/CodeGen/ReadMethodFactory.cs
+++ b/src/Tmds.DBus/CodeGen/ReadMethodFactory.cs
@@ -135,6 +135,8 @@ public static MethodInfo CreateReadMethodForType(Type type) // Type Read(Message
             throw new ArgumentException($"Cannot (de)serialize Type '{type.FullName}'");
         }

+        public static T S_ReadValueTupleStruct<T>(MessageReader reader) => reader.ReadValueTupleStruct<T>();
+
         private static readonly MethodInfo s_messageReaderReadEnum = typeof(MessageReader).GetMethod(nameof(MessageReader.ReadEnum));
         private static readonly MethodInfo s_messageReaderReadBoolean = typeof(MessageReader).GetMethod(nameof(MessageReader.ReadBoolean));
         private static readonly MethodInfo s_messageReaderReadByte = typeof(MessageReader).GetMethod(nameof(MessageReader.ReadByte));
@@ -156,7 +158,7 @@ public static MethodInfo CreateReadMethodForType(Type type) // Type Read(Message
         private static readonly MethodInfo s_messageReaderReadDictionaryObject = typeof(MessageReader).GetMethod(nameof(MessageReader.ReadDictionaryObject), Type.EmptyTypes);
         private static readonly MethodInfo s_messageReaderReadArray = typeof(MessageReader).GetMethod(nameof(MessageReader.ReadArray), Type.EmptyTypes);
         private static readonly MethodInfo s_messageReaderReadStruct = typeof(MessageReader).GetMethod(nameof(MessageReader.ReadStruct), Type.EmptyTypes);
-        private static readonly MethodInfo s_messageReaderReadValueTupleStruct = typeof(MessageReader).GetMethod(nameof(MessageReader.ReadValueTupleStruct), Type.EmptyTypes);
+        private static readonly MethodInfo s_messageReaderReadValueTupleStruct = typeof(ReadMethodFactory).GetMethod(nameof(S_ReadValueTupleStruct), BindingFlags.Static|BindingFlags.Public);
         private static readonly MethodInfo s_messageReaderReadDBusInterface = typeof(MessageReader).GetMethod(nameof(MessageReader.ReadDBusInterface));
     }
 }
```

Arguably, this should be reported as a bug in Mono since it's an incompatibility with .NET. But also, I'm not sure that using delegates in this way is valid according to the spec, since it assumes the calling convention of a static method with 1 argument is the same as an instance method with 0 arguments.

**Comment by tmds** [comment] 2022-05-10 13:51
@madewokherd can you add some reproducer steps?

**Comment by madewokherd** [comment] 2022-05-11 18:58
I encountered this in an AT-SPI2 client project I'm working on: https://github.com/madewokherd/gazelle

The steps that cause a crash for me are:
1. Enable AT-SPI2 in your Linux desktop environment and restart the desktop session.
2. Run gazelle.exe.
3. Do something that creates a new window using a toolkit that's hooked up to AT-SPI2 (for me, clicking the applications menu in xfce was enough). This causes a ChildrenChanged signal which crashes.

**Comment by tmds** [comment] 2022-05-17 07:53
@madewokherd fyi, I'm doing a separate library from Tmds.DBus called Tmds.DBus.Protocol which doesn't use reflection or runtime code generation. For sure, that won't have the issue you're seeing.

If you want to be an early adopter, there is documentation at: https://github.com/tmds/Tmds.DBus/blob/main/docs/protocol.md.

The Tmds.DBus.Tool can generate proxy objects for this library by passing the `--protocol-api` argument to the `codegen` command.

It's a work in progress, though the API should remain pretty stable. I want to have the initial version on nuget.org later this year (October-ish).

**Comment by matihuf** [comment] 2022-09-02 05:49
@madewo, I think I am dealing with the same problem. I am using NetworkManager in my mono project and it's crashing at method 
`Task<(ObjectPath path, ObjectPath activeConnection)> AddAndActivateConnectionAsync(IDictionary<string, IDictionary<string, object>> Connection, ObjectPath Device, ObjectPath SpecificObject);` I saw a pullrequest but it was not merged. You wanted to come back with this later? Any news?

**Comment by madewokherd** [comment] 2022-09-08 21:58
Unfortunately, it seems like the real problem is in Mono's JIT, and I haven't been able to figure out what's going wrong.

**Comment by tmds** [comment] 2024-01-03 13:58
Closing due to lack of a reproducer.

**Closed by tmds** 2024-01-03 13:58 UTC
