### ISSUE TITLE
AddMatch error: Connection ":X.XX" is not allowed to add more match rules

### ISSUE THREAD

**Issue by 5CoVK** [tmds/Tmds.DBus#325] opened 2024-11-21 08:13 UTC
Hello,
I am using a Bluetooth library for .NET ([Linux.Bluetooth](https://github.com/SuessLabs/Linux.Bluetooth)), which uses Tmds.DBus (**0.20.0**) itself.

I noticed that when my software runs, after some time, I always end up with the same DBus error :

`dbus-daemon[489]: [system] Connection ":1.37" is not allowed to add more match rules (increase limits in configuration file if required; max_match_rules_per_connection=2048)`

To give you some context:
My software periodically scans (in Bluetooth) the environment, which creates `InterfacesAdded` messages for each device found, and when the scan ends, the corresponding `InterfacesRemoved ` messages. Most of the time it works, but after some hours/days, some `InterfacesRemoved` are missed, which causes the number of match rules to grow indefinitely until reaching the above error.

There are a lot (at least 50) of Bluetooth devices in my vicinity, and I do multiple 30 seconds scans every 15 minutes.

I already posted an [issue ](https://github.com/SuessLabs/Linux.Bluetooth/issues/19) on the Linux.Bluetooth repo, but we suspect that this issue comes from Tmds.TBus and not from them. Can you think of any scenario where the `InterfacesRemoved ` would not be called ? Have you seen this issue before ?

Don't hesitate to ask me if you need more info from my side,
Thank you very much.

**Comment by tmds** [comment] 2024-11-21 11:38
The match rules get removed when `Dispose` is called on the `IDisposable` returned by the `Watch*` methods.

Have you checked that the library and your code are doing these disposes?

**Comment by tmds** [comment] 2024-11-21 12:03
To find out what match rules are not getting removed, you can use a D-Bus monitoring tool.
Match rules are added with `org.freedesktop.DBus.AddMatch`, and removed with `org.freedesktop.DBus.RemoveMatch`.

If you look at the trace, you should be able to see which are not getting removed.

There are various tools available, like Bustle (GUI), `dbus-monitor` (CLI), the .NET global tool that comes with `Tmds.DBus` allows also supports monitoring (`dotnet dbus monitor`).

**Comment by tmds** [comment] 2024-11-26 18:32
@5CoVK were you able to debug the issue further?

**Comment by 5CoVK** [comment] 2024-11-27 09:46
Thank you @tmds for your quick feedback, I am currently investigating the issue. Unfortunately I don't work full time on this project and I can't make as much progress as i would like to. I'm already familiar with `dbus-monitor` and I'll look into my code and the library to check if/when the `Dispose` is called. I'll let you know how it goes !

**Comment by tmds** [comment] 2024-12-06 09:31
@5CoVK have you made some progress?

**Comment by tmds** [comment] 2024-12-13 09:58
There has been no progress recently so I'm going to close this.
@5CoVK feel free to re-open if [debugging](https://github.com/tmds/Tmds.DBus/issues/325#issuecomment-2490955030) show that the issue is in the `Tmds.DBus` library.

**Closed by tmds** 2024-12-13 09:58 UTC
